### ISSUE TITLE
in-page links redirect back to same page

### ISSUE THREAD

**Issue by danMSFTcorpCookies** [AdobeDocs/commerce-admin.en#1]
Issue in ./help/getting-started/compliance-cookie-law.md

There are links in this page that should be going to specific content/pages.  But, those destination pages redirect back to this page.  Is that intentional?  Should they instead be deeplinks into this same page, such as scrolling to one of the subheadings of this page?

Thanks.
**Dan

**Comment by leslietilling** [comment]
This was fixed. Thanks for letting us know :)
