### ISSUE TITLE
bin/adobe commerce

### ISSUE THREAD

**Issue by j0um** [AdobeDocs/commerce-admin.en#13]
Issue in ./help/inventory-management/cli.md

Hey guys I've tried the bin/Adobe Commerce command but it does not work. :)

**Comment by damienwebdev** [comment]
@leslietilling https://github.com/AdobeDocs/commerce-admin.en/commit/5d26560bfefeb91e4a3d6024eebc523a90362f8e

Looks to have introduced many instances of `bin/Adobe Commerce` across the docs. These need to be reverted to `bin/magento`.

**Comment by leslietilling** [comment]
Fix is here: https://github.com/AdobeDocs/commerce-admin.en/commit/bff07f82bf5853d73f38b751d125ab61c35e8eb4
