### ISSUE TITLE
Incorrect information

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-admin.en#15]
Issue in ./help/stores-purchase/order-archive.md

This section is not accurate and should be re-evaluated:

```
Adobe Commerce Support recommends enabling Order archiving to save MySQL disk space and improve checkout performance. See [Best practices for order placement performance ](https://support.magento.com/hc/en-us/articles/360048170772)in Adobe Commerce Support Knowledge Base.
```

There are no disk savings by implementing this. I'm also not sure how it would improve checkout performance - the linked article only suggests enabling asynchronous order processing: https://support.magento.com/hc/en-us/articles/360048170772

The archive orders functionality removes an order entry from the sales_order_grid table and move it to the magento_sales_order_grid_archive... all the other information will still be saved in the sales_order table.

The idea behind this functionality is that if you have fewer orders in the sales_order_grid table ( the table used by the grid in Sales > Operations > Orders), the load/search of that page will be quicker (the archived orders would be found in “Sales > Archive > Orders” instead)

**Comment by leslietilling** [comment]
@ak77-prime  Vicky B submitted this fix: https://github.com/AdobeDocs/commerce-admin.en/commit/f7cf114d81dd36d7a28d0ddd21d9bda453a72907
