### ISSUE TITLE
Display formatting of the caption

### ISSUE THREAD

**Issue by ak77-prime** [AdobeDocs/commerce-admin.en#16]
Issue in ./help/catalog/product-price-special.md

Is there a formatting issue here?

https://experienceleague.adobe.com/docs/commerce-admin/catalog/products/pricing/product-price-special.html?lang=en#use-a-simple-start-and-end-date
https://experienceleague.adobe.com/docs/commerce-admin/catalog/products/pricing/product-price-special.html?lang=en#set-a-special-price-and-date-range-for-selected-products

![image](https://user-images.githubusercontent.com/68703716/203675737-821fb977-bd77-4246-8f7c-709a086e2952.png)

If I copy the text and paste it, it looks like this:

```
Magento Open Source feature Alternative method required for Magento Open Source ([Learn more](https://experienceleague.adobe.com/docs/commerce-admin/user-guides/home.html?lang=en#product-editions))
```

**Comment by leslietilling** [comment]
@ak77-prime  The "alt text" for the image is part of what you copied. Not sure what your use case is here.

Also, Adobe employees should open issues in internal repository: https://git.corp.adobe.com/AdobeDocs/commerce-admin.en.

**Comment by leslietilling** [comment]
@ak77-prime  It is an icon to represent the OS "code base". The procedure it is different for people running off of that rather than the Commerce product.

**Comment by leslietilling** [comment]
@ak77-prime  Are you OK if I close this?

**Comment by ak77-prime** [comment]
sure
