### ISSUE TITLE
Set Free Shipping to 'For shipment with matching items.'

### ISSUE THREAD

**Issue by cscrewvala** [AdobeDocs/commerce-admin.en#22]
Issue in ./help/merchandising-promotions/price-rules-cart-free-shipping.md

While this documentation page about free shipping says you should add ‘For shipment with matching items’ value on the ‘Free Shipping’ dropdown, this doesn’t work. Free Shipping is not applied on any order - even when no conditions are set for the promotion. 
You have to set the ‘Free Shipping’ dropdown to ‘For matching items only’ value. Then free shipping is applied.

This bug was noted 2 years ago here https://magento.stackexchange.com/questions/331592/magento-2-3-2-free-shipping-cart-rule-not-working

Suggested Update:
from: … ’Set Free Shipping to For shipment with matching items.'
to: … ‘Set Free Shipping to For matching items only.’

There are 2 occurrences of this statement that need changing, and a screencap also. 

---
Additional Notes:
The point of that setting is to designate whether Free Shipping applies only when ALL items in the Cart meet the conditions of the rule, or only when some items meet the rule. 

So the conclusion is that OOTB Free Shipping does not work for specific scenarios when you want certain products to enable free shipping and want to allow free shipping on the whole order even if they don’t meet the conditions. 

Note that this setting may not even work as intended anyway https://github.com/magento/magento2/issues/14206
https://github.com/magento/magento2/issues/34866

But regardless, the documentation should state a condition that actually works.

**Comment by leslietilling** [comment]
Fixed
