### ISSUE TITLE
Incorrect B2B welcome email snapshot - B2B documentation

### ISSUE THREAD

**Issue by gauravharshranosys** [AdobeDocs/commerce-admin.en#25]
Issue in ./help/b2b/account-companies.md

The welcome email screenshot is incorrect. The current screenshot is of the Company Approval Email template which doesn't have any link to set passwords.
The correct email template should be like below:
![image](https://user-images.githubusercontent.com/47966694/215691485-766b164c-6cd5-4733-9e53-17531209204a.png)

**Comment by erikmarr** [comment]
Let's remove the screenshot and make sure we describe what the email will contain.

**Comment by meker12** [comment]
Issue fixed. Content updates published to ExL: https://experienceleague.adobe.com/docs/commerce-admin/b2b/companies/account-companies.html
