### ISSUE TITLE
Meta data section contains wrong screenshot

### ISSUE THREAD

**Issue by arnoudhgz** [AdobeDocs/commerce-admin.en#27]
Issue in ./help/merchandising-promotions/meta-data.md

The screenshot supplied on the page contains a layout that is not actually in the backend. This can be confusing when searching for this section.

![image](https://user-images.githubusercontent.com/10864061/221205147-5fd5d974-1355-4bb0-81fc-3aef71983234.png)

**Comment by pykettk** [comment]
[Document that houses this screenshot](https://github.com/AdobeDocs/commerce-admin.en/blob/main/help/merchandising-promotions/meta-data.md)

**Comment by leslietilling** [comment]
Fixed in https://github.com/AdobeDocs/commerce-admin.en/commit/3b7c406d13fde28bea28d27050f63d922eac830a
