### ISSUE TITLE
Adobe Commerce document on experience cloud is not MTed?

### ISSUE THREAD

**Issue by mkawachi** [AdobeDocs/commerce-admin.en#32]
Issue in ./help/landing/home.md

e.g. https://experienceleague.adobe.com/docs/commerce-admin/user-guides/home.html?lang=ja

This page has MT widget, but even if we change the language to non-English, content won't be localized.

**Comment by dobooth** [comment]
Asked the ExL team about this.

**Comment by leslietilling** [comment]
The commerce-admin translation repos were deleted by the system somehow. They are back in place and pages are now providing MT versions.
