### ISSUE TITLE
'Set up exclusive access' section 

### ISSUE THREAD

**Issue by cscrewvala** [AdobeDocs/commerce-admin.en#41]
Issue in ./help/merchandising-promotions/event-configure.md

'Set up exclusive access' section seems to be a draft of the 'Restrict access' section just below it, so could be deleted?

**Comment by meker12** [comment]
URL to update: https://github.com/AdobeDocs/commerce-admin.en/issues/41

**Comment by meker12** [comment]
Fixed.
