### ISSUE TITLE
'Store View' rather than 'store'

### ISSUE THREAD

**Issue by cscrewvala** [AdobeDocs/commerce-admin.en#42]
Issue in ./help/catalog/category-products-sort.md

"You can set up the category options separately for each [store](https://experienceleague.adobe.com/docs/commerce-admin/stores-sales/site-store/stores.html?lang=en#add-stores) to determine the selection of products, their relative position in the list, and the attributes that are available for category rules."

This should be 'Store View' rather than 'store'. We need to be careful when using the word store to mean the generic sense of ecommerce website, as it is easily confused with a Commerce 'Store' which is a configuration entity

**Comment by meker12** [comment]
Fixed.
