### ISSUE TITLE
No es posible traducir al español

### ISSUE THREAD

**Issue by puertalex** [AdobeDocs/commerce-admin.en#47]
Issue in [./help/getting-started/websites-stores-views.md](https://experienceleague.adobe.com/docs/commerce-admin/start/setup/websites-stores-views.html)

**Comment by danidelcar** [comment]
Hi @puertalex , seems to be running as usual now. You can check [here](https://experienceleague.adobe.com/docs/commerce-admin/start/setup/websites-stores-views.html). Thanks for opening the issue!

**Comment by danidelcar** [comment]
Fixed
